### PR TITLE
Add navic hl groups

### PR DESCRIPTION
**Pull request by fbearoff**
Refactoring of https://github.com/rebelot/kanagawa.nvim/pull/75 for the new overhaul to close https://github.com/rebelot/kanagawa.nvim/issues/62

### CODE REVIEW

**Comment by rebelot** [comment]
Why not linking to corresponding TS captures? Theme Colors should be used semantically, not because of the actual color, i.e. use syn.const because it's a constant not because it's orange. Otherwise we lose portability across themes

**Comment by fbearoff** [comment]
Updated, I've tried to follow the same structure as Cmp for the most part

**Comment by Jomik** [comment]
Should this be merged? Seems to work.

**Comment by lkhphuc** [comment]
Just a ping. Tested and it works well.

**Comment by c3n21** [comment]
No news?

**Comment by syntnc** [comment]
Any updates on this please? navic is fairly commonly used and the commit seems to work well.

**Comment by waynerv** [comment]
This looks good on my machine.

**Pull request merged**
