### PR TITLE
feat(extras): add kanagawa.tmTheme

### PR DESCRIPTION
**Pull request by obergodmar**
Added a `.tmTheme` colorscheme file for [bat](https://github.com/sharkdp/bat), [delta](https://github.com/dandavison/delta), and [lazygit](https://github.com/jesseduffield/lazygit).

I found [this issue](https://github.com/rebelot/kanagawa.nvim/issues/126#issue-1625782962) and decided to migrate colors to `.tmTheme` format myself.

Also it can be used as a repo: https://github.com/obergodmar/kanagawa-tmTheme

It looks like this: 

[bat config](https://github.com/obergodmar/dotfiles/blob/master/.config/bat/config)\
bat

[delta config](https://github.com/obergodmar/dotfiles/blob/master/.gitconfig)\
delta

[lazygit config](https://github.com/obergodmar/dotfiles/blob/master/.config/lazygit/config.yml)\
lazygit

### CODE REVIEW

**Comment by Neved4** [comment]
@obergodmar Is there any way you used to ease the conversion to `.tmTheme`?
Would be cool to have "Dragon" and "Light" variants, see: https://github.com/rebelot/kanagawa.nvim/issues/126#issuecomment-2049558529

**Comment by natematykiewicz** [comment]
Tokyonight has a folder of templates that get used to generate these sort of files. It makes it easy to regenerate them if colors in the color scheme change, or new color schemes get added.

https://github.com/folke/tokyonight.nvim/tree/f247ee700b569ed43f39320413a13ba9b0aef0db/lua/tokyonight/extra

Here's the file that builds a .tmTheme
https://github.com/folke/tokyonight.nvim/blob/f247ee700b569ed43f39320413a13ba9b0aef0db/lua/tokyonight/extra/sublime.lua

It would be nice if Kanagawa did similar.

**Comment by obergodmar** [comment]
> @obergodmar Is there any way you used to ease the conversion to `.tmTheme`? Would be cool to have "Dragon" and "Light" variants, see: [#126 (comment)](https://github.com/rebelot/kanagawa.nvim/issues/126#issuecomment-2049558529)

When I made this PR I didn't even think of "Dragon" and "Light" variants (because personally only used "Wave"). Sure thing they should have been added as well. I'll submit a new PR.

Thanks @natematykiewicz for the links. Looks cool, but lua specific (for sublime/bat/delta/others with tmTheme isn't really suitable imo). Will try to make something shell oriented instead of lua.

**Comment by natematykiewicz** [comment]
Sorry if I was unclear.

Those templates are [used by a script](https://github.com/folke/tokyonight.nvim/blob/9bf9ec53d5e87b025e2404069b71e7ebdc3a13e5/lua/tokyonight/extra/init.lua#L19) to [generate .tmTheme](https://github.com/folke/tokyonight.nvim/tree/9bf9ec53d5e87b025e2404069b71e7ebdc3a13e5/extras/sublime) files.

They allow the template to simply reference color scheme names (like `ui.fg` or `ui.bg` in Kanagawa), and then each color scheme is able to define what those are.

https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/themes.lua

**Comment by obergodmar** [comment]
Hey @Neved4 @natematykiewicz ! I've just published a [PR](https://github.com/rebelot/kanagawa.nvim/pull/231). If you could take a look.

**Pull request merged**
