### PR TITLE
fix(theme) Use config.undercurl when setting up highlights

### LINKED ISSUE #115: config.undercurl is not used in actual config
Noticed that none of the hlgroups settings use `config.undercurl`. They all default to true. 

```
        DiagnosticUnderlineError = { undercurl = true, sp = theme.diag.error },
        DiagnosticUnderlineWarn = { undercurl = true, sp = theme.diag.warning },
        DiagnosticUnderlineInfo = { undercurl = true, sp = theme.diag.info },
        DiagnosticUnderlineHint = { undercurl = true, sp = theme.diag.hint },
```
The intention is to use `config.undercurl` right? I can create a PR. I already verified that it works

### PR DESCRIPTION
**Pull request by kting28**
Allow control of undercurls from config as advertised. Fix #115

### CODE REVIEW

**Comment by rebelot** [comment]
Good catch, must have been wiped during transition... however, we need to fall back to underlines

```lua
SpellBad = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.error },
```

Actually, I am questioning about the usefulness of this setting... nvim already falls back to plain underlines if the terminal does not support undercurls. The only reason for this option would be if users really don't like wavy underlines, but is that enough to justify a "first-class" option?

**Comment by kting28** [comment]
What's a non "first-class" option?  using `config.overrides` ? Since there are quite a few items that reads the configuration, my vote is still for `config.undercurls`.  For me this is more of an accessibility option since the curls made the code underlined hard to see.

**Comment by kting28** [comment]
Sure, not a big deal either way. So what's the solution for the original issue that `config.undercurl` is just plainly not used anywhere? Going back to `SpellBad = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.error },` ?

**Comment by rebelot** [comment]
Yes, I'd stick with that

**Comment by kting28** [comment]
done updated PR

**Pull request merged**
